# Use a imagem oficial do Python como base
FROM python:3.9-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo requirements.txt para o contêiner
COPY requirements.txt .

# Instale as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copie o restante do código da aplicação para o contêiner
COPY . .

# Defina a variável de ambiente para Flask
ENV PORT=5000
ENV FLASK_APP=run.py
ENV FLASK_ENV=production
ENV SMTP_SERVER="smtp.gmail.com"
ENV SMTP_PORT=587
ENV MAIL_OWNER="Nicolas@zedia.com.br"
ENV RECAPTCHA_KEY="6LfxgxgqAAAAABx95eubEPpyRk83xBdIbuclTPwG"
ENV RECAPTCHA_URL="https://www.google.com/recaptcha/api/siteverify"
ENV MAIL_AUTH_USER="nicolasodev@gmail.com"
ENV MAIL_AUTH_PASS="rjrf qwas bouk opar"
ENV TEXT_MAIL_TITLE="Backend Challenge - Nicolas"

# Exponha a porta que o Flask irá rodar
EXPOSE $PORT

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]
