info:
  title: Support-API
  description: API para gerenciar solicitações de suporte de uma empresa
  version: 1.0
server:
  url: Apenas rodando local
  description: Ainda não está em produção


paths:
  /ticket:
    post:
      summary: Abre um novo ticket de suporte
      description: Usuário fez o envio de um ticket de suporte para a empresa
      requestBody:
        required: true
        content: 
          aplication/json:
            schema:
              $ref: '#/components/schemas/ticket'

      responses:
        '201':
          description: Ticket enviado com sucesso
          content: {}
        '400':
          description: Ticket não foi preenchido de maneira correta (Bad Request)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/invalidTicket'
        '401'
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidTicket'
        '500'
          description: Servidor encontrou uma situação que não sabe lidar (Internal Server Error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidTicket'


components:
  schemas:
    ticket:
      type: object
      properties:
        recaptcha:
          type: string
          description: token a ser validado pela API do google
        comment:
          type: string
          description: comentário do cliente, razão pelo qual ele está abrindo o tikcet
        name:
          type: string
          description: nome do cliente
        mail: 
          type: string
          description: email do cliente
        
      invalidTicket:
        type: object
        properties:
          type:
            type: string
            description: URL com mais informações sobre o erro, para erros genéricos recebe "about:blank"
          title:
            type: string
            description: Descreve o tipo de problema
            example: 400 (Bad Request)
          detail:
            type: string
            description: Descrição detalhada do problema
            example: Email inválido / Campo nome não pode estar vazio
          instance:
            type: string
            description: endpoint da API que gerou o erro

            